image: python:latest

# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
#services:
#  - postgres:latest
#
#variables:
#  POSTGRES_DB: nornir
#  POSTGRES_PASSWORD: v3rys3cur1ty

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - cd backend
  - ls
  - rm -rf db.sqlite3
  - python -V  # Print out python version for debugging
  - pip install -r requirements.txt

test_backend:
  stage: test
  variables:
    DB_CONNECTION_STRING: "sqlite:///db.sqlite3"
  script:
    - python manage.py migrate
    - python manage.py create_groups
    - python manage.py testdb_setup
    - pytest -vv
