logging:
  enabled: true
  format: '%(asctime)s - %(name)12s - %(levelname)8s - %(funcName)10s() - %(message)s'
  level: INFO
  log_file: nornir.log
runner:
  options:
    num_workers: 200
  plugin: threaded
